apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      hostname: kafka-consumer
      containers:
        - name: kafka-consumer
          image: kafka-consumer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_ENDPOINT
              value: "kafka-service.kafka.svc.cluster.local:9092"
            - name: WAITING_TIME
              value: "2000"
            - name: TOPIC_NAME
              value: "test-topic"

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer
spec:
  scaleTargetRef:
    name: kafka-consumer
    envSourceContainerName: kafka-consumer
  pollingInterval: 3
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-service.kafka.svc.cluster.local:9092
        consumerGroup: test-group
        topic: test-topic
        lagThreshold: "5"
