apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-server
  name: test-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      labels:
        app: test-server
    spec:
      hostname: test-server
      containers:
        - name: nginx
          image: nginx
          env:
            - name: TEST_ENVIRONMENT
              value: "v2"
